### ISSUE TITLE
在项目里面引入后，安卓启动不了

### ISSUE THREAD

**Issue by webmaster404** [OpenFlutter/nautilus#1]
错误信息：
* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@label value=(youhuijishi) from AndroidManifest.xml:18:9-36
  	is also present at [com.taobao.android:securityguardaar3:5.1.81] AndroidManifest.xml:26:9-41 value=(@string/app_name).
  	Suggestion: add 'tools:replace="android:label"' to <application> element at AndroidManifest.xml:16:5-39:19 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

版本：nautilus: ^0.0.6
在yaml注释之后，项目就可以正常运行

**Comment by JarvanMo** [comment]
@luganhuo   参看：[AndroidManifest.xml](https://github.com/OpenFlutter/nautilus/blob/master/example/android/app/src/main/AndroidManifest.xml)。
```
tools:replace="android:label"
```

**Comment by funengqing** [comment]
按如下处理可解决这个问题
1. 在manifest节点加上：xmlns:tools="http://schemas.android.com/tools‘’
2. 在application 节点加上：android:label="项目的名字"
3. 在application 节点加上：tools:replace="android:label"

最终的AndroidManifest.xml如下：
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="你的包名"
xmlns:tools="http://schemas.android.com/tools">

<uses-permission android:name="android.permission.INTERNET"/>
<application
    android:label="项目的名字"
    tools:replace="android:label"
    ></application>
</manifest>
