### ISSUE TITLE
没有用鉴定完毕

### ISSUE THREAD

**Issue by Slhaos7373** [OpenFlutter/nautilus#10]
里面的开发者的adzoneId是写死的，而且应该是被他内部加密写进去的，目前没有我是没有找到怎么改 xml文件改了也没有用 ，也就是授权登录只是授权他的淘宝号，估计就是吸粉用的  浪费我时间

**Comment by JarvanMo** [comment]
你是在逗我？？？如果你觉得哪有问题就PR，别在这里阴阳怪气的。看好了，这个项目是别人花钱让我做的，并应客户要求将其开源，并且项目已上线。你和我在说吸粉，可笑不。

**Comment by JarvanMo** [comment]
吸粉对我来说有什么意义吗？给我发钱还是咋地。

**Comment by Slhaos7373** [comment]
那想请问下 为什么跳转授权一直是授权别的的开发者账号 adzoneId登录的时候 或者初始化为什么没有

**Comment by JarvanMo** [comment]
你要是觉得有问题就指出来并PR，别整个`应该是被他内部加密写进去的`。

**Comment by JarvanMo** [comment]
还有业务上的事情别问我，我不懂。我的客户已经用上了，并且没有问题。其他的自己对百川SDK。

**Comment by JarvanMo** [comment]
而且我已经说过无数次，我只负责SDK的桥接，至于百川电商业务上的事情我根本不了解。写plugin也不需要对业务有了解。

**Comment by Slhaos7373** [comment]
行了行了 大神  你厉害行了吧，你那个微信的还可以，就是这个不行

**Comment by JarvanMo** [comment]
别和我阴阳怪气的，OK？我应该能猜出来你是群里的哪位。你有能力你就PR，别整个应该加密，引用的SDK都是淘宝官方SDK，natilus代码都是开源的，在这和我说什么加密？要么你自己做个插件，自己慢慢对百川SDK。加个百川SDK官方群也比在这里阴阳怪气强。真是搞笑了，我做个开源项目，还整出阴谋论了。

**Comment by JarvanMo** [comment]
别自己弄不出来，就整个阴谋论。

**Comment by Slhaos7373** [comment]
我只是很想知道 你的adzoneId是怎么初始化载入的

**Comment by Slhaos7373** [comment]
flutter我前后也弄了半年 好歹我也独立做出来一个项目  也没那么菜的

**Comment by JarvanMo** [comment]
没那么菜不会自己看代码？不会自己看百川SDK官方demo？不会加百川旺旺群问问？你看plugin有传adzone id?我都不知道什么是你口中的adzone id 是什么，你却莫须有地给我来个阴谋论？我有必要去篡改百川SDK？我还能改了百川的maven?
