### ISSUE TITLE
openUrl 过去没有小把手

### ISSUE THREAD

**Issue by fuiyu** [OpenFlutter/nautilus#12]
我对比了一下原生，发现用的方法是一样的，都是AlibcTrade.show，不知道为何没有出现返回app的小把手，我简单集成的是有的，我的代码
![image](https://user-images.githubusercontent.com/14845298/61097043-4ca88500-a48c-11e9-978a-eecc313ae9fe.png)

**Comment by JarvanMo** [comment]
这个我也不太清楚。

**Comment by tustman** [comment]
请求这个插件支持ios平台吗？

**Comment by fuiyu** [comment]
include of non-modular header inside framework module 'nautilus.NautilusPlugin'  构建刚刚试了一下出错了

**Comment by JarvanMo** [comment]
@fuiyu 这个百度一下。

**Comment by JarvanMo** [comment]
@tustman 支持的。

**Comment by fuiyu** [comment]
@JarvanMo 这个问题好了，出现了另外一个问题。`uncaught exception 'NSInvalidArgumentException', reason: '+[AlibcTradeCommonSDK alibc_initMonitor]: unrecognized selector sent to class 0x105d594a0'`，不知道是哪里集成错了

**Comment by fuiyu** [comment]
在pod 下的 targets找到 nautilus 下的other linker flag 增加-ObjC 可解决，具体要怎么解决插件问题，需要专业ios看看了

**Comment by JarvanMo** [comment]
@fuiyu 强！我对ios是真不熟悉。好像不是所有的工程都需要回linker flag。具体的我也不知道怎么弄。

**Comment by fuiyu** [comment]
@JarvanMo 我也不是iOS的开发人员,百度说`-ObjC`：加了这个参数后，链接器就会把静态库中所有的Objective-C类和分类都加载到最后的可执行文件中 ,你可以尝试在podspec添加 ` s.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-lObjC' }`

**Comment by JarvanMo** [comment]
@fuiyu OK。直接可以PR的。
