### ISSUE TITLE
在安卓8.0系统会闪退 是不是和极光推送有冲突？

### ISSUE THREAD

**Issue by Slhaos7373** [OpenFlutter/nautilus#13]

**Comment by JarvanMo** [comment]
有日志吗。

**Comment by Slhaos7373** [comment]
我release包的，那部手机识别不了 用你说的arm64好像不行

**Comment by JarvanMo** [comment]
没有日志解决不了

**Comment by Slhaos7373** [comment]
W/AppMonitor( 5734): load ut_c_api.so failed
W/LoginSDK( 5734): ************************************
W/LoginSDK( 5734): Debug is enabled, make sure to turn it off in the production environment
W/LoginSDK( 5734): ************************************
I/mtopsdk.SDKConfig( 5734): [setGlobalAppVersion]set appVersion=3.1.1.210
D/mtopsdk.Mtop( 5734): [init] ttid=null
I/mtopsdk.MtopSDK( 5734): [init]ttid=null
I/mtopsdk.MtopSDK( 5734): [init]MtopSDK init Called
I/mtopsdk.MtopSDK( 5734): [executeInitCoreTask]MtopSDK initcore start. ttid=null
D/mtopsdk.AsyncServiceBinder( 5734): [asyncBind]try to bind service for a
W/mtopsdk.AsyncServiceBinder( 5734): [asyncBind]service framework not exist. use intent to bind service.
D/mtopsdk.AsyncServiceBinder( 5734): [asyncBind]bindService ret=false
D/mtopsdk.SecuritySignImpl( 5734): [init]SecuritySignImpl ISign init.set GlobalAppKey=27660457
D/mtopsdk.SecuritySignImpl( 5734): [init]SecuritySignImpl ISign init succeed.init time=5
I/mtopsdk.XState( 5734): [setValue]Attention :User XState Local Mode: key:appKey value:27660457
I/mtopsdk.MtopSDK( 5734): [executeInitCoreTask]MtopSDK initcore end
I/mtopsdk.MtopSDK( 5734): [executeInitExtraTask]MtopSDK initextra start
I/mtopsdk.MtopSDK( 5734): [executeInitExtraTask]MtopSDK initextra end
E/AuthSDK_kernel( 5734): timeStamp=1564906937000
E/AuthSDK_kernel( 5734): time =2019-08-04 16:24:12 602
D/AuthSDK_( 5734): sdk version = 1.4.3
D/AuthSDK_( 5734): time =2019-08-04 16:24:12 630
E/AuthSDK_( 5734): utdid = XUaVuCAk1LcDABZsd75moNyY
E/AuthSDK_( 5734): time =2019-08-04 16:24:12 636
D/AuthSDK_kernel( 5734): registerRpc
D/AuthSDK_kernel( 5734): time =2019-08-04 16:24:12 690
D/mtopsdk.TBSdkLog( 5734): [setTLogEnabled] tLogEnabled=false
D/mtopsdk.TBSdkLog( 5734): [setPrintLog] printLog=true
I/mtopsdk.SDKConfig( 5734): [setGlobalAppVersion]set appVersion=3.3.6
D/AuthSDK_kernel( 5734): registerStorage
D/AuthSDK_kernel( 5734): time =2019-08-04 16:24:12 888
D/AuthSDK_kernel( 5734): registerUserTrack
D/AuthSDK_kernel( 5734): time =2019-08-04 16:24:12 930
D/NetworkSecurityConfig( 5734): No Network Security Config specified, using platform default
I/zygote  ( 5734): Background concurrent copying GC freed 15506(1062KB) AllocSpace objects, 14(280KB) LOS objects, 59% free, 1055KB/2MB, paused 35.627ms total 443.007ms
D/AuthSDK_kernel( 5734): register login service
D/AuthSDK_kernel( 5734): time =2019-08-04 16:24:13 934
D/AuthSDK_Member.LoginLifecycleAdapter( 5734): LoginLifecycle init 
D/AuthSDK_Member.LoginLifecycleAdapter( 5734): time =2019-08-04 16:24:13 936
D/AuthSDK_kernel( 5734): register account link service
D/AuthSDK_kernel( 5734): time =2019-08-04 16:24:13 941
D/AuthSDK_Member.AccountLinkLifecycleAdapter( 5734): AccountLinkLifecycleAdapter init 
D/AuthSDK_Member.AccountLinkLifecycleAdapter( 5734): time =2019-08-04 16:24:13 942
D/AuthSDK_syncRun( 5734): INIT SUCCESS
D/AuthSDK_syncRun( 5734): time =2019-08-04 16:24:13 991
D/AuthSDK_asyncRun( 5734): SUCCESS
D/AuthSDK_asyncRun( 5734): time =2019-08-04 16:24:14 022
I/mtop.rb-RemoteBusiness( 5734): [seq:RB0.MTOP1]|start request api=[mtop.taobao.tbk.sdk.config]
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=uid
D/mtopsdk.MtopProxyBase( 5734): [seq:MTOP1]|[validateBusinessInit]MtopRequest [ apiName=mtop.taobao.tbk.sdk.config, version=1.0, data={"mcid":"tunion4android@02:00:00:00:00:00","appVersion":"3.3.6","os":"android8.0.0","aliapp":"","deviceModel":"Android SDK built for x86","sdkVersion":"0.3.2","packageName":"com.jingjiang.liang"}, needEcode=false, needSession=true]
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=lat
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=t_offset
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=sid
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=accessToken
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=utdid
I/mtopsdk.MtopFeatureManager( 5734): [setMtopFeatureFlag] set feature=UNIT_INFO_FEATURE , openFlag=true
I/mtopsdk.MtopFeatureManager( 5734): [setMtopFeatureFlag] set feature=SUPPORT_UTDID_UNIT , openFlag=true
I/mtopsdk.MtopFeatureManager( 5734): [setMtopFeatureFlag] set feature=DISABLE_X_COMMAND , openFlag=true
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=ttid
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=sid
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=ua
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=t_offset
D/mtop.rb-RemoteAuth( 5734): com.alibaba.baichuan.trade.biz.auth.c@204aa0e
I/mtopsdk.XState( 5734): [setValue]Attention :User XState Local Mode: key:ttid value:2014_0_27660457@baichuan_android_3.1.1.210
I/flutter ( 5734): 初始化结果：true
D/AuthSDK_login( 5734): auth goLogin
D/AuthSDK_login( 5734): time =2019-08-04 16:24:14 387
D/AndroidRuntime( 5734): Shutting down VM
E/AndroidRuntime( 5734): FATAL EXCEPTION: main
E/AndroidRuntime( 5734): Process: com.jingjiang.liang, PID: 5734
E/AndroidRuntime( 5734): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jingjiang.liang/com.ali.auth.third.ui.LoginActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
E/AndroidRuntime( 5734):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
E/AndroidRuntime( 5734):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
E/AndroidRuntime( 5734):        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime( 5734):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
E/AndroidRuntime( 5734):        at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime( 5734):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 5734):        at android.app.ActivityThread.main(ActivityThread.java:6541)
E/AndroidRuntime( 5734):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5734):        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/AndroidRuntime( 5734):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
E/AndroidRuntime( 5734): Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
E/AndroidRuntime( 5734):        at android.app.Activity.onCreate(Activity.java:986)
E/AndroidRuntime( 5734):        at com.ali.auth.third.ui.LoginActivity.onCreate(LoginActivity.java:30)
E/AndroidRuntime( 5734):        at android.app.Activity.performCreate(Activity.java:6975)
E/AndroidRuntime( 5734):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
E/AndroidRuntime( 5734):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
E/AndroidRuntime( 5734):        ... 9 more
I/WebViewFactory( 5734): Loading com.android.chrome version 58.0.3029.125 (code 303012512)
I/cr_LibraryLoader( 5734): Time to load native libraries: 5 ms (timestamps 531-536)
I/chromium( 5734): [INFO:library_loader_hooks.cc(140)] Chromium logging enabled: level = 0, default verbosity = 0
I/cr_LibraryLoader( 5734): Expected native library version number "58.0.3029.125", actual native library version number "58.0.3029.125"
W/mtopsdk.XState( 5734): [getValue]Attention :User XState Local Mode : key=t_offset
W/mtopsdk.ApiLockHelper( 5734): [lock], currentTime=1564907054, lockentity=LockedEntity [key=mtop.taobao.tbk.sdk.config$1.0, lockStartTime=1564907054, lockInterval=10]
D/mtopsdk.MtopStatistics( 5734): [seq:MTOP1]|MtopStatistics [Detail]:startTime=889923,mtopResponseParseStartTime=890735,mtopResponseParseEndTime=890737,endTime=890737
D/mtopsdk.MtopStatistics( 5734): MtopStatistics[sumstat(ms)]:mtopOneWayTime=814,oneWayTime=781,mtopResponseParseTime=2,httpResponseStatus=420,ret=ANDROID_SYS_API_FLOW_LIMIT_LOCKED
I/mtop.rb-FinishListener( 5734): [seq:RB0.MTOP1]|Mtop onFinish event received.

**Comment by JarvanMo** [comment]
Only fullscreen opaque activities can request orientation.android 8.0的bug

**Comment by Slhaos7373** [comment]
应该咋做 知道吗

**Comment by Slhaos7373** [comment]
或者说现在有处理方案了吗

**Comment by JarvanMo** [comment]
百度
