### ISSUE TITLE
mac10.14.5 运行github的案例会报错

### ISSUE THREAD

**Issue by qq329401134** [OpenFlutter/nautilus#14]
=== BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    ld: warning: ignoring file /Users/zhuzhao/Desktop/nautilus-master/ios/Frameworks/UTDID.framework/UTDID, file was built for unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x43 0x75 0x72 0x72 0x65 0x6E 0x74 ) which is not the architecture being linked (arm64): /Users/zhuzhao/Desktop/nautilus-master/ios/Frameworks/UTDID.framework/UTDID
    ld: warning: ignoring file /Users/zhuzhao/Desktop/nautilus-master/ios/Frameworks/UTMini.framework/UTMini, file was built for unsupported file format ( 0x56 0x65 0x72 0x73 0x69 0x6F 0x6E 0x73 0x2F 0x43 0x75 0x72 0x72 0x65 0x6E 0x74 ) which is not the architecture being linked (arm64): /Users/zhuzhao/Desktop/nautilus-master/ios/Frameworks/UTMini.framework/UTMini
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_UT", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcUTMiniAdapter.o)
      "_OBJC_CLASS_$_UTSecuritySDKRequestAuthentication", referenced from:
          objc-class-ref in AlibabaAuthExt(ALBBUTUserTrack.o)
          objc-class-ref in AlibcTradeCommon(AlibcUTMiniAdapter.o)
      "_OBJC_CLASS_$_UTOirginalCustomHitBuilder", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcUTMiniAdapter.o)
      "_OBJC_CLASS_$_AppMonitorMeasureValueSet", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcTradeAppMonitorAdapter.o)
      "_OBJC_CLASS_$_UTDevice", referenced from:
          objc-class-ref in AlibabaAuthExt(ALBBSecurityStorageImpl.o)
          objc-class-ref in AlibcLinkPartnerSDK(ALPJumpAppService.o)
          objc-class-ref in AlibcLinkPartnerSDK(ALPDegradeService.o)
          objc-class-ref in AlibcTradeCommon(AlibcTradeCommonSDK.o)
          objc-class-ref in OpenMtopExt(MtopSetupRequstBeforeFilter.o)
          objc-class-ref in OpenMtopExt(TBSDKConfiguration.o)
      "_OBJC_CLASS_$_AppMonitorAlarm", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcTradeAppMonitorAdapter.o)
      "_OBJC_CLASS_$_AppMonitorDimensionSet", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcTradeAppMonitorAdapter.o)
      "_OBJC_CLASS_$_AppMonitorMeasureSet", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcTradeAppMonitorAdapter.o)
      "_OBJC_CLASS_$_AppMonitorStat", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcTradeAppMonitorAdapter.o)
      "_OBJC_CLASS_$_AppMonitorDimensionValueSet", referenced from:
          objc-class-ref in AlibcTradeCommon(AlibcTradeAppMonitorAdapter.o)
      "_OBJC_CLASS_$_UTCustomHitBuilder", referenced from:
          objc-class-ref in AlibabaAuthExt(ALBBUTUserTrack.o)
      "_OBJC_CLASS_$_UTAnalytics", referenced from:
          objc-class-ref in AlibabaAuthExt(ALBBUTUserTrack.o)
          objc-class-ref in AlibcTradeCommon(AlibcUTMiniAdapter.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the precompiled application for the device.

**Comment by JarvanMo** [comment]
ios不懂。

**Comment by qq329401134** [comment]
IOS这块是只写了代码实现没有写配置什么的对吗

**Comment by JarvanMo** [comment]
应该不需要配置什么。反正我的客户用了是没什么问题。

**Comment by qq329401134** [comment]
是我手欠配置错了哈哈哈，确实不用配置啥
