### ISSUE TITLE
安卓9报错 compileSdkVersion 28

### ISSUE THREAD

**Issue by flutterbest** [OpenFlutter/nautilus#18]
报错信息和这里的一样 ：

https://github.com/aliyun/alicloud-android-demo/issues/197

改为27就好了 但是这样很多手机不兼容 啊

**Comment by JarvanMo** [comment]
我看看能不能升级sdk。

**Comment by flutterbest** [comment]
> 我看看能不能升级sdk。

谢谢 方便加个微信不

**Comment by flutterbest** [comment]
为什么不支持用V5的sdk  我们的还是V4的

**Comment by flutterbest** [comment]
> 我看看能不能升级sdk。

另外 能不能写一个自定义webview的

**Comment by JarvanMo** [comment]
1.这个项目本身就是给我的客户做的。
2.我没有任何百川经验。
3.时间精力有限。

**Comment by JarvanMo** [comment]
> > 我看看能不能升级sdk。
> 
> 谢谢 方便加个微信不

可以加我们的QQ群。

**Comment by flutterbest** [comment]
谢谢，我自己处理吧

**Comment by JarvanMo** [comment]
欢迎PR。开源项目不能指望一个人。我一个人实在是精力有限。谢谢。

**Comment by tustman** [comment]
@niugengyun 小哥 你好 请问这个问题怎么解决呢？ 我们引入这个插件后也 出现了这个报错：
` java.lang.IllegalAccessException: void android.os.SystemProperties.<init>() is not accessible from java.lang.Class<com.alibaba.mtl.log.e.d>`
