### ISSUE TITLE
请问有没有遇到，图片appkey和bundle id不一致的情况

### ISSUE THREAD

**Issue by fuiyu** [OpenFlutter/nautilus#21]
要抓狂了，bundle id对了好多遍，也下载了v4的图片，不知道为什么一直说不正确

**Comment by fuiyu** [comment]
不知道你们有没有遇到。。。我直接把百川的 bundled id改了，生成图片直接使用百川插件的bid，不用app的bid，解决了，深坑，希望有熟悉ios的技术人员来优化

**Comment by cnyunguo** [comment]
> 不知道你们有没有遇到。。。我直接把百川的 bundled id改了，生成图片直接使用百川插件的bid，不用app的bid，解决了，深坑，希望有熟悉ios的技术人员来优化

百川插件的bid在哪儿看？

**Comment by fuiyu** [comment]
> > 不知道你们有没有遇到。。。我直接把百川的 bundled id改了，生成图片直接使用百川插件的bid，不用app的bid，解决了，深坑，希望有熟悉ios的技术人员来优化
> 
> 百川插件的bid在哪儿看？

org.cocoapods.nautilus
