### ISSUE TITLE
iOS授权提示Error Domain=AlibabaAuthSDK Code=104 "TB_BACK_WITHOUT_AUTH" UserInfo={NSLocalizedDescription=TB_BACK_WITHOUT_AUTH}

### ISSUE THREAD

**Issue by hekaiyou** [OpenFlutter/nautilus#5]
iOS端使用淘宝授权的时候，总返回Code = 104，授权失败，请问大佬是怎么解决的

**Comment by hekaiyou** [comment]
问题解决了，要在AppDelegate.m文件里面添加下面的代码：

#include "AppDelegate.h"
#include "GeneratedPluginRegistrant.h"
#include <AlibcTradeSDK/AlibcTradeSDK.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application
    didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [GeneratedPluginRegistrant registerWithRegistry:self];
  // Override point for customization after application launch.
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation{
    // 如果百川处理过会返回YES
    if (![[AlibcTradeSDK sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation]) {
        // 处理其他app跳转到自己的app
    }
    return YES;
}

//IOS9.0 系统新的处理openURL 的API
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options {
    __unused BOOL isHandledByALBBSDK=[[AlibcTradeSDK sharedInstance] application:application openURL:url options:options];//处理其他app跳转到自己的app，如果百川处理过会返回YES
    return YES;
}

@end

**Comment by hekaiyou** [comment]
希望作者大大把这个添加到文档里面去，避免后面的人踩坑了哈

**Comment by JarvanMo** [comment]
可以选择发起一个PR
