### ISSUE TITLE
Instance of 'LoginResult'

### ISSUE THREAD

**Issue by cnyunguo** [OpenFlutter/nautilus#7]
nautilus.login().then((data){
 print(data);
});

回调返回：
Instance of 'LoginResult'

**Comment by JarvanMo** [comment]
有什么问题吗

**Comment by cnyunguo** [comment]
你好，我使用您的示例跑了一下，login没有反应，有闪一下，我们一块来看一下这个问题，可以加一下微信吗，15801057714
