### ISSUE TITLE
openUrl后返回回来是一个白框

### ISSUE THREAD

**Issue by qq329401134** [OpenFlutter/nautilus#8]
每次openUrl后返回会有下面的图，可不可以隐藏掉
![image](https://user-images.githubusercontent.com/38587734/60329625-5083d400-99c3-11e9-874e-58bf9274a726.png)

**Comment by JarvanMo** [comment]
非插件本身问题，无法解答

**Comment by qq329401134** [comment]
这个白框应该是加载js然后跳转到淘宝的吧，可以弄成那种hide模式加载js然后跳到后台嘛？就像是webviewplugin的hidden:true一样@JarvanMo

**Comment by JarvanMo** [comment]
这个页面都是SDK做的，你可以加他们旺旺群咨询。

**Comment by qq329401134** [comment]
好的，谢谢了
