### ISSUE TITLE
is any english documentation or describe about libary?

### ISSUE THREAD

**Issue by pishguy** [OpenFlutter/nautilus#9]

**Comment by JarvanMo** [comment]
not yet.This library is for [Baichuan E-commerce SDK](https://baichuan.taobao.com/product/esdk.htm?spm=a3c0d.7662652.1998907869.3.100abe48nhFI5i).`Baichuan E-commerce SDK` is from Ali. I think most users are from China. So if anyone who wants English document, I'll try it.
